export type UsState = {
  code: string;
  name: string;
  courts: string;
  selfHelp: string;
  statutes: string;
  legalAid: string;
  labor: string;
  smallClaims: string;
};

export const US_STATES: UsState[] = [
  { code: "AL", name: "Alabama", courts: "https://judicial.alabama.gov/", selfHelp: "https://judicial.alabama.gov/", statutes: "https://alison.legislature.state.al.us/code-of-alabama", legalAid: "https://www.alabamalegalhelp.org/", labor: "https://labor.alabama.gov/", smallClaims: "District court small-claims limits vary — confirm with the clerk." },
  { code: "AK", name: "Alaska", courts: "https://courts.alaska.gov/", selfHelp: "https://courts.alaska.gov/shc/index.htm", statutes: "https://www.akleg.gov/basis/statutes.asp", legalAid: "https://alaskalawhelp.org/", labor: "https://labor.alaska.gov/", smallClaims: "District court small-claims limits vary — confirm with the clerk." },
  { code: "AZ", name: "Arizona", courts: "https://www.azcourts.gov/", selfHelp: "https://www.azcourts.gov/selfservicecenter", statutes: "https://www.azleg.gov/arizonarevisedstatutes/", legalAid: "https://www.azlawhelp.org/", labor: "https://www.azica.gov/", smallClaims: "Justice court limits vary by county — confirm with the clerk." },
  { code: "AR", name: "Arkansas", courts: "https://www.arcourts.gov/", selfHelp: "https://www.arcourts.gov/access-to-justice", statutes: "https://www.arkleg.state.ar.us/", legalAid: "https://www.arlegalservices.org/", labor: "https://www.labor.arkansas.gov/", smallClaims: "District court small-claims limits vary — confirm with the clerk." },
  { code: "CA", name: "California", courts: "https://www.courts.ca.gov/", selfHelp: "https://selfhelp.courts.ca.gov/", statutes: "https://leginfo.legislature.ca.gov/", legalAid: "https://www.lawhelpca.org/", labor: "https://www.dir.ca.gov/", smallClaims: "Statewide small-claims limits are published on the courts.ca.gov self-help site — confirm current amount." },
  { code: "CO", name: "Colorado", courts: "https://www.courts.state.co.us/", selfHelp: "https://www.courts.state.co.us/Self_Help/Index.cfm", statutes: "https://leg.colorado.gov/agencies/office-legislative-legal-services/colorado-revised-statutes", legalAid: "https://www.coloradolegalservices.org/", labor: "https://cdle.colorado.gov/", smallClaims: "County court small-claims limits vary — confirm with the clerk." },
  { code: "CT", name: "Connecticut", courts: "https://www.jud.ct.gov/", selfHelp: "https://www.jud.ct.gov/selfhelp/", statutes: "https://www.cga.ct.gov/current/pub/titles.htm", legalAid: "https://ctlawhelp.org/", labor: "https://portal.ct.gov/dol", smallClaims: "Small-claims (also called magistrate) limits — confirm on jud.ct.gov." },
  { code: "DE", name: "Delaware", courts: "https://courts.delaware.gov/", selfHelp: "https://courts.delaware.gov/help/", statutes: "https://delcode.delaware.gov/", legalAid: "https://www.delegalhelplink.org/", labor: "https://labor.delaware.gov/", smallClaims: "Justice of the Peace Court handles many small-claims — confirm the current cap." },
  { code: "DC", name: "District of Columbia", courts: "https://www.dccourts.gov/", selfHelp: "https://www.dccourts.gov/services/self-help", statutes: "https://code.dccouncil.gov/", legalAid: "https://www.lawhelp.org/dc", labor: "https://does.dc.gov/", smallClaims: "D.C. Superior Court Small Claims — confirm the current cap with the clerk." },
  { code: "FL", name: "Florida", courts: "https://www.flcourts.gov/", selfHelp: "https://www.flcourts.gov/Resources-Services/Office-of-Family-Courts/Family-Court-in-Florida/Family-Law-Self-Help-Information", statutes: "http://www.leg.state.fl.us/statutes/", legalAid: "https://www.floridalawhelp.org/", labor: "https://floridajobs.org/", smallClaims: "County court small-claims limits vary — confirm with the clerk." },
  { code: "GA", name: "Georgia", courts: "https://georgiacourts.gov/", selfHelp: "https://georgialegalaid.org/", statutes: "https://www.legis.ga.gov/", legalAid: "https://www.georgialegalaid.org/", labor: "https://dol.georgia.gov/", smallClaims: "Magistrate court limits vary — confirm with the clerk." },
  { code: "HI", name: "Hawaii", courts: "https://www.courts.state.hi.us/", selfHelp: "https://www.courts.state.hi.us/self-help", statutes: "https://www.capitol.hawaii.gov/hrscurrent/", legalAid: "https://www.lawhelp.org/hi", labor: "https://labor.hawaii.gov/", smallClaims: "District court small-claims limits — confirm with the clerk." },
  { code: "ID", name: "Idaho", courts: "https://isc.idaho.gov/", selfHelp: "https://courtselfhelp.idaho.gov/", statutes: "https://legislature.idaho.gov/statutesrules/idstat/", legalAid: "https://www.idaholegalaid.org/", labor: "https://www.labor.idaho.gov/", smallClaims: "Magistrate small-claims department: money or property up to $15,000 under Idaho Code 1-2301 as published — confirm the current code and local filing fee with the clerk." },
  { code: "IL", name: "Illinois", courts: "https://www.illinoiscourts.gov/", selfHelp: "https://www.illinoislegalaid.org/", statutes: "https://www.ilga.gov/legislation/ilcs/ilcs.asp", legalAid: "https://www.illinoislegalaid.org/", labor: "https://labor.illinois.gov/", smallClaims: "Circuit court small-claims limits vary by county — confirm with the clerk." },
  { code: "IN", name: "Indiana", courts: "https://www.in.gov/courts/", selfHelp: "https://www.in.gov/courts/selfservice/", statutes: "https://iga.in.gov/laws/current/ic", legalAid: "https://www.indianalegalservices.org/", labor: "https://www.in.gov/dol/", smallClaims: "Small-claims dockets (often township or city courts) — confirm local cap and forms." },
  { code: "IA", name: "Iowa", courts: "https://www.iowacourts.gov/", selfHelp: "https://www.iowacourts.gov/for-the-public/representing-yourself/", statutes: "https://www.legis.iowa.gov/law/iowaCode", legalAid: "https://www.iowalegalaid.org/", labor: "https://www.iowaworkforcedevelopment.gov/", smallClaims: "Small-claims limits — confirm on iowacourts.gov." },
  { code: "KS", name: "Kansas", courts: "https://www.kscourts.gov/", selfHelp: "https://www.kscourts.gov/Public/Self-Help", statutes: "https://www.ksrevisor.org/statutes.html", legalAid: "https://www.kansaslegalservices.org/", labor: "https://www.dol.ks.gov/", smallClaims: "Small-claims limits — confirm with the district court clerk." },
  { code: "KY", name: "Kentucky", courts: "https://kycourts.gov/", selfHelp: "https://kycourts.gov/Legal-Help/Pages/default.aspx", statutes: "https://legislature.ky.gov/Law/Statutes/Pages/default.aspx", legalAid: "https://www.kyjustice.org/", labor: "https://labor.ky.gov/", smallClaims: "District court small-claims — confirm the current cap." },
  { code: "LA", name: "Louisiana", courts: "https://www.lasc.org/", selfHelp: "https://www.louisiana.gov/government/judicial/", statutes: "https://legis.la.gov/legis/LawSearch.aspx", legalAid: "https://louisianalawhelp.org/", labor: "https://www.laworks.net/", smallClaims: "City/parish court limits vary — confirm with the clerk." },
  { code: "ME", name: "Maine", courts: "https://www.courts.maine.gov/", selfHelp: "https://www.courts.maine.gov/help/index.html", statutes: "https://legislature.maine.gov/statutes/", legalAid: "https://ptla.org/", labor: "https://www.maine.gov/labor/", smallClaims: "Small-claims limits — confirm with the clerk." },
  { code: "MD", name: "Maryland", courts: "https://www.mdcourts.gov/", selfHelp: "https://www.mdcourts.gov/legalhelp", statutes: "https://mgaleg.maryland.gov/mgawebsite/Laws/Statutes", legalAid: "https://www.peoples-law.org/", labor: "https://www.dllr.state.md.us/", smallClaims: "District Court small-claims — confirm current cap on mdcourts.gov." },
  { code: "MA", name: "Massachusetts", courts: "https://www.mass.gov/orgs/massachusetts-court-system", selfHelp: "https://www.mass.gov/representing-yourself-in-a-civil-case", statutes: "https://malegislature.gov/Laws/GeneralLaws", legalAid: "https://www.masslegalhelp.org/", labor: "https://www.mass.gov/orgs/executive-office-of-labor-and-workforce-development", smallClaims: "Small-claims sessions — confirm current cap with the clerk." },
  { code: "MI", name: "Michigan", courts: "https://www.courts.michigan.gov/", selfHelp: "https://www.courts.michigan.gov/srl/", statutes: "https://www.legislature.mi.gov/", legalAid: "https://michiganlegalhelp.org/", labor: "https://www.michigan.gov/leo", smallClaims: "District court small-claims — confirm current cap." },
  { code: "MN", name: "Minnesota", courts: "https://www.mncourts.gov/", selfHelp: "https://www.mncourts.gov/Help-Topics.aspx", statutes: "https://www.revisor.mn.gov/statutes/", legalAid: "https://www.lawhelpmn.org/", labor: "https://www.dli.mn.gov/", smallClaims: "Conciliation court — confirm current cap on mncourts.gov." },
  { code: "MS", name: "Mississippi", courts: "https://courts.ms.gov/", selfHelp: "https://courts.ms.gov/", statutes: "https://www.legislature.ms.gov/", legalAid: "https://www.mslegalservices.org/", labor: "https://www.mdes.ms.gov/", smallClaims: "Justice court limits vary — confirm with the clerk." },
  { code: "MO", name: "Missouri", courts: "https://www.courts.mo.gov/", selfHelp: "https://www.courts.mo.gov/page.jsp?id=630", statutes: "https://revisor.mo.gov/main/Home.aspx", legalAid: "https://www.lsemo.org/", labor: "https://labor.mo.gov/", smallClaims: "Small-claims division — confirm current cap with the clerk." },
  { code: "MT", name: "Montana", courts: "https://courts.mt.gov/", selfHelp: "https://courts.mt.gov/Forms", statutes: "https://leg.mt.gov/bills/mca/index.html", legalAid: "https://www.mtlsa.org/", labor: "https://dli.mt.gov/", smallClaims: "Small-claims limits — confirm with the clerk." },
  { code: "NE", name: "Nebraska", courts: "https://supremecourt.nebraska.gov/", selfHelp: "https://supremecourt.nebraska.gov/self-help", statutes: "https://nebraskalegislature.gov/laws/laws.php", legalAid: "https://www.legalaidofnebraska.org/", labor: "https://dol.nebraska.gov/", smallClaims: "Small-claims court — confirm current cap." },
  { code: "NV", name: "Nevada", courts: "https://nvcourts.gov/", selfHelp: "https://nvcourts.gov/supreme/court_information/self_help", statutes: "https://www.leg.state.nv.us/NRS/", legalAid: "https://nlslaw.net/", labor: "https://labor.nv.gov/", smallClaims: "Justice court small-claims — confirm local cap." },
  { code: "NH", name: "New Hampshire", courts: "https://www.courts.nh.gov/", selfHelp: "https://www.courts.nh.gov/self-help-center", statutes: "https://www.gencourt.state.nh.us/rsa/html/indexes/", legalAid: "https://nhlegalaid.org/", labor: "https://www.nh.gov/nhes/", smallClaims: "Circuit court small-claims — confirm current cap." },
  { code: "NJ", name: "New Jersey", courts: "https://www.njcourts.gov/", selfHelp: "https://www.njcourts.gov/self-help", statutes: "https://www.njleg.state.nj.us/", legalAid: "https://www.lsnjlaw.org/", labor: "https://www.nj.gov/labor/", smallClaims: "Special Civil Part small-claims — confirm current cap." },
  { code: "NM", name: "New Mexico", courts: "https://www.nmcourts.gov/", selfHelp: "https://www.nmcourts.gov/self-help/", statutes: "https://nmonesource.com/nmos/en/nav.do", legalAid: "https://www.lawhelpnewmexico.org/", labor: "https://www.dws.state.nm.us/", smallClaims: "Magistrate/metro court limits vary — confirm with the clerk." },
  { code: "NY", name: "New York", courts: "https://www.nycourts.gov/", selfHelp: "https://www.nycourts.gov/courthelp/", statutes: "https://www.nysenate.gov/legislation/laws", legalAid: "https://www.lawhelpny.org/", labor: "https://dol.ny.gov/", smallClaims: "City, town, and village small-claims limits vary — confirm with the court that issued the paper." },
  { code: "NC", name: "North Carolina", courts: "https://www.nccourts.gov/", selfHelp: "https://www.nccourts.gov/help-topics", statutes: "https://www.ncleg.gov/Laws/GeneralStatutes", legalAid: "https://www.legalaidnc.org/", labor: "https://www.labor.nc.gov/", smallClaims: "Magistrate small-claims — confirm current cap." },
  { code: "ND", name: "North Dakota", courts: "https://www.ndcourts.gov/", selfHelp: "https://www.ndcourts.gov/legal-self-help", statutes: "https://www.ndlegis.gov/general-information/north-dakota-century-code", legalAid: "https://www.legalassist.org/", labor: "https://www.nd.gov/labor/", smallClaims: "Small-claims — confirm current cap with the clerk." },
  { code: "OH", name: "Ohio", courts: "https://www.supremecourt.ohio.gov/", selfHelp: "https://www.ohiolegalhelp.org/", statutes: "https://codes.ohio.gov/", legalAid: "https://www.ohiolegalhelp.org/", labor: "https://jfs.ohio.gov/", smallClaims: "Municipal/county small-claims — confirm local cap." },
  { code: "OK", name: "Oklahoma", courts: "https://www.oscn.net/", selfHelp: "https://www.oscn.net/v4/", statutes: "https://www.oscn.net/applications/oscn/index.asp?ftdb=STOKST&level=1", legalAid: "https://oklaw.org/", labor: "https://oklahoma.gov/labor.html", smallClaims: "Small-claims docket — confirm current cap." },
  { code: "OR", name: "Oregon", courts: "https://www.courts.oregon.gov/", selfHelp: "https://www.courts.oregon.gov/programs/selfhelp/Pages/default.aspx", statutes: "https://www.oregonlegislature.gov/bills_laws/pages/ors.aspx", legalAid: "https://oregonlawhelp.org/", labor: "https://www.oregon.gov/boli", smallClaims: "Small-claims — confirm current cap with the clerk." },
  { code: "PA", name: "Pennsylvania", courts: "https://www.pacourts.us/", selfHelp: "https://www.pacourts.us/learn", statutes: "https://www.legis.state.pa.us/cfdocs/legis/LI/Public/cons_index.cfm", legalAid: "https://www.palawhelp.org/", labor: "https://www.dli.pa.gov/", smallClaims: "Magisterial District Court limits vary — confirm with the issuing court." },
  { code: "RI", name: "Rhode Island", courts: "https://www.courts.ri.gov/", selfHelp: "https://www.courts.ri.gov/PublicResources/forms/Pages/default.aspx", statutes: "https://webserver.rilegislature.gov/Statutes/", legalAid: "https://www.helprilaw.org/", labor: "https://dlt.ri.gov/", smallClaims: "Small-claims — confirm current cap." },
  { code: "SC", name: "South Carolina", courts: "https://www.sccourts.org/", selfHelp: "https://www.sccourts.org/selfHelp/", statutes: "https://www.scstatehouse.gov/code/statmast.php", legalAid: "https://www.sclegal.org/", labor: "https://www.llr.sc.gov/", smallClaims: "Magistrate court limits vary — confirm with the clerk." },
  { code: "SD", name: "South Dakota", courts: "https://ujs.sd.gov/", selfHelp: "https://ujs.sd.gov/Legal_Help/", statutes: "https://sdlegislature.gov/Statutes", legalAid: "https://sdlawhelp.org/", labor: "https://dlr.sd.gov/", smallClaims: "Small-claims — confirm current cap." },
  { code: "TN", name: "Tennessee", courts: "https://www.tncourts.gov/", selfHelp: "https://www.tncourts.gov/programs/self-help-center", statutes: "https://www.capitol.tn.gov/", legalAid: "https://www.tals.org/", labor: "https://www.tn.gov/workforce.html", smallClaims: "General sessions small-claims — confirm local cap." },
  { code: "TX", name: "Texas", courts: "https://www.txcourts.gov/", selfHelp: "https://www.txcourts.gov/programs-services/self-help/", statutes: "https://statutes.capitol.texas.gov/", legalAid: "https://texaslawhelp.org/", labor: "https://www.twc.texas.gov/", smallClaims: "Justice court small-claims — confirm current cap on texaslawhelp.org or with the clerk." },
  { code: "UT", name: "Utah", courts: "https://www.utcourts.gov/", selfHelp: "https://www.utcourts.gov/en/self-help.html", statutes: "https://le.utah.gov/xcode/code.html", legalAid: "https://www.utahlegalservices.org/", labor: "https://laborcommission.utah.gov/", smallClaims: "Small-claims — confirm current cap on utcourts.gov." },
  { code: "VT", name: "Vermont", courts: "https://www.vermontjudiciary.org/", selfHelp: "https://www.vermontjudiciary.org/self-help", statutes: "https://legislature.vermont.gov/statutes/", legalAid: "https://vtlawhelp.org/", labor: "https://labor.vermont.gov/", smallClaims: "Small-claims — confirm current cap." },
  { code: "VA", name: "Virginia", courts: "https://www.vacourts.gov/", selfHelp: "https://www.vacourts.gov/courts/cib/home.html", statutes: "https://law.lis.virginia.gov/vacode/", legalAid: "https://www.valegalaid.org/", labor: "https://www.doli.virginia.gov/", smallClaims: "General District Court small-claims — confirm current cap." },
  { code: "WA", name: "Washington", courts: "https://www.courts.wa.gov/", selfHelp: "https://www.courts.wa.gov/forms/", statutes: "https://app.leg.wa.gov/rcw/", legalAid: "https://www.washingtonlawhelp.org/", labor: "https://www.lni.wa.gov/", smallClaims: "District court small-claims — confirm current cap." },
  { code: "WV", name: "West Virginia", courts: "https://www.courtswv.gov/", selfHelp: "https://www.courtswv.gov/public-resources", statutes: "https://code.wvlegislature.gov/", legalAid: "https://www.lawv.net/", labor: "https://labor.wv.gov/", smallClaims: "Magistrate court limits vary — confirm with the clerk." },
  { code: "WI", name: "Wisconsin", courts: "https://www.wicourts.gov/", selfHelp: "https://www.wicourts.gov/services/public/selfhelp.htm", statutes: "https://docs.legis.wisconsin.gov/statutes/prefaces/toc", legalAid: "https://www.legalaction.org/", labor: "https://dwd.wisconsin.gov/", smallClaims: "Small-claims — confirm current cap with the clerk." },
  { code: "WY", name: "Wyoming", courts: "https://www.courts.state.wy.us/", selfHelp: "https://www.courts.state.wy.us/legal-assistances-and-forms/court-self-help-forms/", statutes: "https://wyoleg.gov/StateStatutes/StatutesConstitution", legalAid: "https://www.lawhelp.org/wy", labor: "https://dws.wyo.gov/", smallClaims: "Circuit court small-claims — confirm current cap." },
];

export const NATIONAL_LINKS = [
  { label: "Find legal aid (Legal Services Corporation)", href: "https://www.lsc.gov/about-lsc/what-legal-aid/get-legal-help" },
  { label: "LawHelp.org directory", href: "https://www.lawhelp.org/" },
  { label: "ABA Free Legal Answers / Find Legal Help", href: "https://www.findlegalhelp.org/" },
  { label: "Federal courts locator", href: "https://www.uscourts.gov/about-federal-courts/federal-courts-public" },
  { label: "U.S. Department of Labor Wage and Hour", href: "https://www.dol.gov/agencies/whd" },
  { label: "CourtListener (opinions — not advice)", href: "https://www.courtlistener.com/" },
];

export function getState(code: string): UsState {
  return US_STATES.find((s) => s.code === code) ?? US_STATES.find((s) => s.code === "ID")!;
}

export function stateByName(name: string): UsState | undefined {
  const n = name.trim().toLowerCase();
  return US_STATES.find((s) => s.name.toLowerCase() === n || s.code.toLowerCase() === n);
}
